name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out the code
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=sonarqube-gitaction 
            -Dsonar.projectKey=sonarqube-gitaction_gitaction-poc-10-java-ci
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io
            # -Dsonar.java.binaries=./target/classes
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
